# Generated by Django 3.1.2 on 2020-10-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=9)),
                ('_type', models.CharField(choices=[('1', 'Lecture'), ('2', 'Tutorial'), ('3', 'Lab')], max_length=8)),
                ('timeslot', models.CharField(choices=[('1', '09:00-10:30'), ('2', '10:40-12:10'), ('3', '12:40-14:10'), ('4', '14:20-15:50'), ('5', '16:00-17:30'), ('6', '17:40-19:10'), ('7', '19:20-20:50')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16)),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('_type', models.CharField(choices=[('1', 'Lecture'), ('2', 'Tutorial'), ('3', 'Lab')], max_length=8)),
                ('can_hold', models.ManyToManyField(to='courses.Class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
