# Generated by Django 3.1.2 on 2020-11-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('BS', 'Bachelor'), ('MS', 'Master')], default='BS', max_length=16),
        ),
    ]
