# Generated by Django 3.1.2 on 2020-11-07 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=19, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
